### ISSUE TITLE
Unhandled exception when moving multiple segments and using Dropbox output

### ISSUE THREAD

**Issue by haz429** [ShikenNuggets/Chatbot-Integration-Component-for-LiveSplit#1]
As far as I'm aware this only happens with a Dropbox output, as I've tested it with a local folder with no problems. This unhandled exception arises when trying to use the "Move up" or "Move down" buttons in the Splits Editor (usually with multiple segments). I assume that this amount of updates is too much for Dropbox to handle, thus giving the error. I can confirm that this does not happen with Chatbox Integration unloaded.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at ChatBotIntegration.CBIComponent.UpdateData()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at LiveSplit.View.TimerForm.editor_RunEdited(Object sender, EventArgs e)
   at LiveSplit.View.RunEditorDialog.RaiseRunEdited()
   at LiveSplit.View.RunEditorDialog.TimesModified()
   at LiveSplit.View.RunEditorDialog.SegmentList_ListChanged(Object sender, ListChangedEventArgs e)
   at System.ComponentModel.ListChangedEventHandler.Invoke(Object sender, ListChangedEventArgs e)
   at System.ComponentModel.BindingList`1.OnListChanged(ListChangedEventArgs e)
   at System.ComponentModel.BindingList`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at LiveSplit.View.RunEditorDialog.SwitchSegments(Int32 segIndex)
   at LiveSplit.View.RunEditorDialog.btnMoveDown_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ShikenNuggets** [comment]
Should be resolved in the [newest release](https://github.com/ShikenNuggets/Chatbot-Integration-Component-for-LiveSplit/releases/tag/v1.0.2). It's only a band-aid fix, still need to address the underlying issues, but this is fine for now.
